[package]
name = "cavalier-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = { version = "0.2.100" }
web-sys = { version = "0.3.77", features = ["Window", "Document", "HtmlElement", "Text"] }

[profile.release]
opt-level = "s"
