name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: bookworm-slim

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for the axum backend
      run: docker build . --file Dockerfile --tag cavalier-backend:$(date +%s)
